# Generated by Django 4.2.13 on 2024-08-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMesaServicio', '0005_alter_user_usertipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userTipo',
            field=models.CharField(choices=[('Administrativo', 'Administrativo'), ('Instructor', 'Instructor')], db_comment='Tipo de usuario', max_length=15),
        ),
    ]
